puts CronDescriber.parse("* * * * *")
puts CronDescriber.parse("0 * * * *")
puts CronDescriber.parse("0 9 * * 1")
puts CronDescriber.parse("30 18 * * 5")
puts CronDescriber.parse("0 0 1 1 *")
puts CronDescriber.parse("*/5 * * * *")
puts CronDescriber.ordinalize(1)
puts CronDescriber.ordinalize(2)
puts CronDescriber.ordinalize(11)
puts CronDescriber.ordinalize(21)
