puts Escape.shell_single_word("")
puts Escape.shell_single_word("foo")
puts Escape.shell_single_word("*")
puts Escape.shell_command(["ls", "/"])
puts Escape.shell_command(["echo", "*"])
puts Escape.uri_segment("a/b")
puts Escape.uri_path("a?b/c?d")
puts Escape.html_text("a & b < c > d")
puts Escape.html_attr("ab&<>\"c")
