puts RadiantSiteTemplatesExtension.class
puts RadiantSiteTemplatesExtension.is_a?(Module)
puts RadiantSiteTemplatesExtension.name
puts RadiantSiteTemplatesExtension.ancestors.include?(RadiantSiteTemplatesExtension)
