require "fileutils"
require "json"

module Bundler
  module Spinel
    # First-party PORT — the complement of Mirror (mirror.rb). A mirror
    # reimplements a foreign gem's narrowed contract; a port converts a gem
    # WE OWN, whose source already compiles under the subset, into spin
    # package shape (matz/spinel docs/internals/spin.md R2) **in place, on a
    # git checkout**:
    #
    #   lib/<name>.rb   ->  <name>.rb          (package root = require root)
    #   lib/<name>/     ->  <name>/            (subfeatures)
    #   spin.toml       generated from the gemspec ([package] name/version)
    #   spinel-ext.json translated to a REPORT: which units carried-C picks
    #                   up as-is, and which need hand-written [[build]] /
    #                   [features] blocks (optional units, pkg-config cflags)
    #
    # Like mirror-init, this is a porter tool a human finishes: it never
    # rewrites the gemspec (dual RubyGems/spin shipping is the owner's
    # decision — the report prints the suggested `require_paths` change),
    # never touches CI, and never publishes. Reference conversion:
    # spinelkit@20a8242 ("convert to spin package"), which this tool
    # mechanizes. First consumer: tep (tep#234).
    #
    # Internal `require "<name>/..."` calls need no rewriting: inside a spin
    # project the package root is a require root, so the gem's own absolute
    # requires resolve unchanged. `require_relative` is position-dependent —
    # the report flags any that reach across the old lib/ boundary.
    module Port
      module_function

      def run(dir, dry: false, out: $stdout)
        dir = File.expand_path(dir)
        spec_file = Dir[File.join(dir, "*.gemspec")].first or
          raise Error, "port: no *.gemspec in #{dir}"
        spec = Gem::Specification.load(spec_file) or
          raise Error, "port: could not load #{spec_file}"
        name    = spec.name
        version = spec.version.to_s
        todos   = []
        moves   = []

        # --- layout conversion (git mv so history follows) ------------------
        lib = File.join(dir, "lib")
        if File.exist?(File.join(lib, "#{name}.rb"))
          moves << ["lib/#{name}.rb", "#{name}.rb"]
        end
        if Dir.exist?(File.join(lib, name))
          moves << ["lib/#{name}", name]
        end
        raise Error, "port: #{dir} has no lib/#{name}.rb or lib/#{name}/ — already ported?" if moves.empty?

        leftovers = Dir.exist?(lib) ? Dir.children(lib) - ["#{name}.rb", name] : []
        unless leftovers.empty?
          todos << "lib/ has entries outside the #{name} namespace: #{leftovers.join(', ')} — move or fold them by hand (spin's require root is the package root; stray top-level names would claim require strings)."
        end

        moves.each do |from, to|
          out.puts "#{dry ? '[dry] ' : ''}git mv #{from} #{to}"
          system("git", "-C", dir, "mv", from, to, exception: true) unless dry
        end
        unless dry
          # drop lib/ if the moves emptied it
          if Dir.exist?(lib) && Dir.children(lib).empty?
            Dir.rmdir(lib)
            out.puts "rmdir lib/ (empty)"
          end
        end

        # --- cross-boundary require_relative audit ---------------------------
        offenders = []
        Dir.glob(File.join(dir, dry ? "lib/" : "", "{#{name}.rb,#{name}/**/*.rb}")).each do |f|
          File.readlines(f, chomp: true).each_with_index do |l, i|
            next unless l =~ /^\s*require_relative\s+["'](\.\.\/)+lib\//
            offenders << "#{f.sub(dir + '/', '')}:#{i + 1}: #{l.strip}"
          end
        end
        unless offenders.empty?
          todos << "require_relative paths still reach across the old lib/ boundary:\n    " + offenders.join("\n    ")
        end

        # --- spin.toml --------------------------------------------------------
        manifest = File.join(dir, "spin.toml")
        if File.exist?(manifest)
          todos << "spin.toml already exists — left untouched; check [package] version matches #{version}."
        else
          toml = +"# spin package manifest — #{name} as an ordinary spin package.\n"
          toml << "# Generated by `spinel-compat port`; the package NAME is the require\n"
          toml << "# string. Repo keeps its historical name (publish convention:\n"
          toml << "# spinel-#{name} for new repos; existing first-party repos stay put).\n"
          toml << "[package]\n"
          toml << "name = \"#{name}\"\n"
          toml << "version = \"#{version}\"\n"
          deps = spec.runtime_dependencies
          unless deps.empty?
            toml << "\n[dependencies]\n"
            deps.each do |d|
              toml << "#{d.name} = \"#{d.requirement}\"   # from the gemspec — verify the spin-index has it\n"
              todos << "dependency `#{d.name}` (#{d.requirement}) declared from the gemspec — it must exist as a spin package (index, git, or path) or be removed."
            end
          end
          out.puts "#{dry ? '[dry] ' : ''}write spin.toml ([package] #{name} #{version})"
          File.write(manifest, toml) unless dry
        end

        # --- spinel-ext.json -> native model report ---------------------------
        ext_file = File.join(dir, "spinel-ext.json")
        if File.exist?(ext_file)
          units = JSON.parse(File.read(ext_file)).reject { |u| u.keys == ["_comment"] }
          srcs  = units.select { |u| u["source"] }
          srcs.group_by { |u| u["name"] }.each do |uname, parts|
            optional = parts.any? { |p| p["optional"] }
            pkgcfg   = parts.filter_map { |p| p["pkg_config"] }.uniq
            src      = parts.filter_map { |p| p["source"] }.first
            new_src  = src&.sub(%r{^lib/}, "")
            if optional
              todos << "ext unit `#{uname}` (#{new_src}) is OPTIONAL (disabled_cflags #{parts.filter_map { |p| p['disabled_cflags'] }.join(' ')}): carried-C would compile it unconditionally — gate it behind [features] with a [[build]] entry (cc -c with the define/pkg-config in `command`), or make the source compile clean without the lib and let ffi_lib resolution fail loud."
            else
              note = pkgcfg.empty? ? "plain cc" : "needs `pkg-config --cflags #{pkgcfg.join(' ')}` — carried-C compiles with bare cc + package-tree includes; system headers usually resolve, verify on a clean box"
              todos << "ext unit `#{uname}` (#{new_src}): carried-C will pick the .c up automatically (#{note}); link flags ride the source's ffi_lib/SPINEL_LINK markers."
            end
          end
          build_units = units.select { |u| u["build"] }
          build_units.each do |u|
            todos << "ext unit `#{u['name']}` has a BUILD entry (#{u.dig('build', 'tool')}) — translate to a [[build]] block (workdir/patches/command/artifacts/exclude; see toy's spin.toml for the reference shape)."
          end
          todos << "spinel-ext.json stays for the bundler-spinel vendor path until consumers migrate — keep the two native descriptions in lockstep."
        end

        # --- tests -------------------------------------------------------------
        testdir = File.join(dir, "test")
        if Dir.exist?(testdir)
          entries = Dir.glob(File.join(testdir, "*.rb")).map { |f| File.basename(f) }
          todos << "spin test runs each top-level test/*.rb as a snapshot program (currently: #{entries.take(4).join(', ')}#{entries.size > 4 ? ', …' : ''}). Harness-style runners (run_all/helpers) belong in test/ SUBDIRS; standalone parity programs stay top-level. `spin test --regen` freezes .expected snapshots."
        else
          todos << "no test/ — add at least one top-level test/*.rb (spin publish runs `spin test` as a hard gate)."
        end

        todos << "gemspec: for dual RubyGems shipping set `spec.require_paths = [\".\"]` and widen `spec.files` to the new layout — owner's call, not auto-edited."

        out.puts "\nPORT REPORT — #{name} #{version} (#{dry ? 'dry run' : 'applied'})"
        todos.each_with_index { |t, i| out.puts "  #{i + 1}. #{t}" }
        out.puts "\nNext: finish the TODOs, `spin build`/`spin test` against a current toolchain, then commit."
        { name: name, version: version, moves: moves, todos: todos }
      end
    end
  end
end
